<section class="news-feed-section terms-and-conditions section-gap component" >
    <div class="container">
<div style="display: flex;flex-direction: column;gap: 10px">
    <h1 class="text-black mt-2">Terms and Conditions</h1>
    <p><a class="text-black" href="http://www.kochibluetigers.com">www.kochibluetigers.com</a> is the property of and belongs to Enigmatic Smile Rewards Private Limited ("ESRPL"). ESRPL is the owner and promoter of the ‘Kochi Blue Tigers' professional twenty20 cricket team ("Team"). Please read these terms and conditions carefully, before interacting on the Website. By accessing, browsing or using this Website, you agree and acknowledge that you have read, understood and agree to be bound by the following terms and conditions of use ("Terms").
    </p>
    <p>The terms 'us' or 'we' or 'our' refer to ESRPL, the owner and operator of the Website. The terms 'user', 'you', or 'your' refer to the user or viewer of the Website.</p>
    <p>ESRPL reserves the right to add, modify, amend, cancel, limit, vary or change, either wholly, or in part, at any point in time, these Terms, without prior notice. Further, ESRPL reserves the right to withdraw, suspend, alter, modify, change, or vary the Website, the Website features, the Website content or parts thereof, at its sole discretion, without prior notice. All modifications/amendments to the Terms will be posted on the Website and will become effective immediately upon such posting to the Website. Your continued use of the Website after such change or modification shall be deemed to be your agreement to the revised/modified Terms. Please review these Terms regularly to remain informed of any changes. If you do not agree to these Terms, please discontinue using this Website immediately.</p>
    <h5 class="text-black mt-2">Website Access, Services and Availability:</h5>
    <p>This Website is made available free of charge. However, ESRPL reserves the right to charge subscription, membership or other fees from a user, in respect of certain product(s) or service(s) provided on this Website. ESRPL may make available certain products, services, content and other functionalities through the Website ("Services"). The Services offered on the Website may differ from time to time and from region to region. Further, ESRPL reserves the right to terminate or cancel any access or order or redirect a user to a different website, at its sole discretion. ESRPL does not make any warranty or representation that a user in one region may access, use or obtain the Services from the Website in another region.</p>
    <h5 class="text-black mt-2">Registration:</h5>
    <p>In general, you can access and visit our Website without registering on the Website or otherwise revealing your identity or any personal information about yourself. However, access to certain Services and products, as well as the ability to interact and comment on certain features and Content (defined herein) of the Website, require completion of a simple registration process to create a User Profile (defined herein). The registration and creation of a User Profile requires you to reveal your identity and/or other information about yourself, as set out herein. Please refer to our Privacy Policy for more information on the kind of information we collect/store and how we use this information.</p>
    <h5 class="text-black mt-2">User Profile:</h5>
    <p>Users will have an option to register with us and create a personal user profile on the Website ("User Profile"), which may enable them to interact on our Website by liking/ commenting on/ sharing the Content available on our Website, and avail of certain Services. ESRPL may, at its sole and absolute discretion, refuse to accept registration applications for the registration and creation of a User Profile.
    </p>
    <p>To create a User Profile, you will be required to provide your full name, email address, mobile number, date of birth, gender, state and city and also choose a password for your User Profile.</p>
    <p>Where appropriate, you may be required to give further information about yourself for your User Profile verification. In order to complete your User Profile, you will be required to provide your full name, email address, gender, mobile number(s), date of birth, current city/place of residence, gender and profile picture. You must provide complete and accurate information about yourself. You undertake that you will notify us and update this information to keep it current. Any information provided by you to us should be complete and truthful to the best of your knowledge. We are not obliged to cross-check or verify information provided by you and we will not take any responsibility for any outcome or consequence as a result of you providing incorrect information or concealing any relevant information from us.
    </p>
    <p>You understand that it is your responsibility to protect the information you provide on the Website including but not limited to your username, password, email address, contact details and mobile number. You are responsible for maintaining the confidentiality of the password and User Profile, and are fully responsible for all activities that occur under your password or User Profile.</p>
    <p>Our Services and our Website are intended for a general audience. You must be at least 18 years of age to create a User Profile or purchase our products or services and we reserve the right to remove your User Profile if we reasonably believe you are under 18.</p>
    <h5 class="text-black mt-2">Website Content:</h5>
    <p>Subject to these Terms, all materials, including illustrations, statements, opinions, articles, views, photographs, products, images, artwork, designs, text, graphics, logos, button icons, images, audio and video clips, and software (collectively, "Content") appearing on this Website are owned or controlled by ESRPL and/or its subsidiaries, affiliates, licensors and content suppliers and are protected by worldwide design, trademark, trade dress, copyright and other intellectual property laws. To the extent content is user generated by users, fans, or other third-party content providers on certain sections of this Website, ESRPL does not screen or review such content as a matter of course, and the contributors of such content remain wholly responsible for all such contributions. If you seek to rely on any representation of information contained on this Website, any such reliance shall be at your own risk.</p>
    <p>This Website and the Content therein are intended solely for personal, non-commercial use by the users of this Website. You may not copy Content from this Website, or otherwise modify, obscure, or delete any copyright or other proprietary notices on this Website. No right, title, or interest in any materials or software, if applicable, on this Website is transferred to you from your use of this Website. You may not reproduce, publish, transmit, distribute, display, modify, create derivative works from, sell, or participate in any sale of, or exploit in any way, in whole or in part, any of the Content, this Website, or any related software without the prior written authorization of ESRPL.</p>
    <h5 class="text-black mt-2">Contributed Content:</h5>
    <p>You are responsible for any notes, comments, images, messages, e-mails, billboard postings, photos, drawings, profiles, opinions, ideas, videos, audio files or other materials (collectively, "User Content") posted or transmitted by you to the Website. It is clarified that ESRPL reserves the right from time to time to determine and modify the manner and circumstances under which any User Content may be submitted, posted, and/or transmitted by users on the Website. Users with a registered User Profile may be permitted to post certain User Content (such as comments and messages) to respond and react to, as well as interact with, certain Content posted on the Website and User Content posted by other User Profiles on the Website. You agree that any User Content posted by you may be used by ESRPL, including for the creation of derivative works that might include such User Content, consistent with its Privacy Policy and Terms as mentioned herein and you will not be entitled to any payment or other compensation for such use. You may not use the Website in any improper or unlawful manner or in breach of any legislation or license that applies to you. You agree to comply with all reasonable instructions that we may provide from time to time regarding the use of the Website. You also agree to allow ESRPL to post or provide a link to any User Content that you have posted on the Website. To the extent you make any contribution of any User Content to the Website, you grant ESRPL and its affiliates, service providers, licensors, and associates a perpetual, royalty-free, worldwide, sub-licensable right and license to use, reproduce, publish, edit, distribute, transfer, store, transmit, publicly display and adapt such User Content in any medium whatsoever whether or not currently known. In contributing such User Content, you represent and warrant to ESRPL that the User Content is your original work of authorship or that you otherwise have the right to make such contribution and grant the aforesaid licenses to ESRPL</p>
    <h5 class="text-black mt-2">Impermissible Use of the Website:</h5>
    <p>Users of this Website shall not host, display, upload, post, comment, modify, publish, transmit, update, or share any User Content that:</p>
    <p>belongs to another person and to which the user does not have any right to;</p>
    <p>is harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libelous, invasive of another's rights including but not limited to rights of celebrity, privacy and intellectual property, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatsoever;</p>
    <p>harms minors in any way;</p>
    <p>infringes any patent, trademark, trade secret, copyright, or other intellectual, proprietary rights, privacy rights, or other right of any party;</p>
    <p>violates any law for the time being in force;</p>
    <p>deceives or misleads the addressee about the origin of such messages or communicates any information that is offensive or menacing in nature;</p>
    <p>impersonates another person or entity or falsely states or otherwise misrepresents your affiliation with any individual or entity;</p>
    <p>disrupts or interferes with any other user's use, access, and/or enjoyment of the Website;</p>
    <p>contains software viruses or any other computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer resource (including, without limitation, a computer virus, malware, logic bombs, Trojan horses, worms, harmful components, corrupted data or other malicious software or harmful data);</p>
    <p>threatens the unity, integrity, defense, security, or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offense or prevents investigation of any offense or is insulting any other nation.</p>
    <h5 class="text-black mt-2">User Rewards Programme:</h5>
    <p>Based on a User Profile's activity and interaction on the Website, including the contribution of creative and positive User Content in response to certain Content posted on the Website and User Content posted by other User Profiles, ESRPL may from time to time recognize select User Profiles, in such manner as determined at ESRPL's discretion, and reward the registered users of such User Profiles with prizes such as team merchandise or Team match tickets as determined at ESRPL's discretion from time to time ("Rewards Programme"). The Rewards Programme shall be implemented by ESRPL in such manner as determined at ESRPL's discretion, and may also be subject to additional special terms and conditions.</p>
    <p>You hereby acknowledge and agree that you shall be eligible to take part in the Rewards Programme only in the event that you are a registered user with a complete User Profile on the Website. In addition, unless otherwise expressly specified by ESRPL, a registered user with a complete User Profile shall be eligible to participate in the Rewards Programme only if he/she is a resident of India. In this respect, you acknowledge and agree that you may be required to submit a valid proof of address to ESRPL, to substantiate your eligibility to participate in the Rewards Programme. You further acknowledge and agree that any prize(s) offered to you under the Rewards Programme are strictly for your own personal non-commercial use, and may be subject to additional terms and conditions</p>
    <p>ESRPL reserves the right to modify, update, cancel, or terminate the Rewards Programme or any part thereof, at any time. The nature of the prizes under the Rewards Programme may be modified or revised by ESRPL from time to time at its discretion. In the event that you breach any of these Terms, and/or any special terms and conditions applicable to the Rewards Programme and/or the prize, ESRPL reserves the right, at its discretion, to: (i) cancel the award of any prize(s) that you may have won under the Rewards Programme, and/or (ii) cancel your participation in the Rewards Programme, and/or (iii) terminate your User Profile.</p>
    <h5 class="text-black mt-2">Warranty and Liability Disclaimer:</h5>
    <p>All content, information, and materials (including Content) on this Website are provided to you on an "AS IS" and "AS AVAILABLE" basis, without warranty or guarantee of any kind, either express or implied. Particularly, no warranty regarding fitness for a particular purpose; uninterrupted access, security; accuracy, completeness, or up-to-date information; or freedom from errors, virus, malware, Trojans, bugs, worms, infections, etc., is given in connection with this Website or use thereof. Further, ESRPL makes no representations or warranties of any kind, express or implied, as to the operation of this Website, the information, the Content, User Content, materials or products included. Except to the extent as provided by the applicable law, ESRPL disclaims all responsibility as to the information, Content, User Content, materials, or products arising from the use of this Website, whether direct, indirect, consequential, or otherwise.</p>
    <p>ESRPL does not warrant that: (i) this Website will be constantly available, or available at all; or (ii) the information on this Website is complete, true, accurate, or not misleading.</p>
    <p>To the fullest extent permissible under applicable laws, you hereby agree to release, discharge and absolve ESRPL, the Team, its affiliates, partners, sponsors, subsidiaries, agents, employees, officers, directors and representatives ("ESRPL Indemnified Parties"), from any and all claims, losses, and damages arising out of the use of, or inability to use, the Website; unavailability, withdrawal, modification, suspension, interruption, discontinuance or variation of the Website; or inability to access or use the Website and the ESRPL Indemnified Parties shall not be liable for any direct, indirect, incidental, special, punitive or consequential damages.</p>
    <p>This Website is controlled and operated from India and ESRPL makes no representation that the content, information, or materials made available herein are appropriate or will be available for use in other locations. Access and use of this Website from outside of India is entirely at your sole risk and you agree and undertake to be responsible for compliance with all applicable local laws and agree to release, discharge, and absolve the ESRPL Indemnified Parties from any liability or loss in this respect.</p>
    <p>ESRPL reserves the right to introduce and initiate new features, functionalities, and components to the Website and/or change, alter, modify, suspend, discontinue, or remove the existing ones without any prior notice to you. Further, ESRPL is entitled to discontinue (either permanently or temporarily) one or more of the Services provided or terminate the Website without any prior notice to you. ESRPL may also prescribe certain limits on the use of the Website and/or Services or storage of Content and/or User Content at its sole discretion without any prior notice to you while at all times comply with the Privacy Policy. In consideration for ESRL granting you access to and use of the Website and Services, you agree that ESRPL and its third-party providers and partners may place such advertising on the Services or in connection with the display of Content, User Content, or information from the Services, whether submitted by them or others.</p>
    <h5 class="text-black mt-2">Accuracy of Information:</h5>
    <p>The information presented on this Website has been compiled by ESRPL from internal and external sources. No representation is made, or warranty given as to the completeness or accuracy of such information. This Website may contain typographical errors and incomplete or out-of-date information. ESRPL reserves the right to make changes to the Content, User Content, and information on this Website or to the Services described therein, or update such information at any time without notice, but ESRPL makes no commitment to correct or update this information.</p>
    <p>Third-party interaction and links to third-party sites:</p>
    <p>The Website may contain links to other third-party websites that are not owned, operated, or endorsed by ESRPL and you hereby release and discharge the ESRPL Indemnified Parties from any and all claims, losses, and damages arising out of the use of, or inability to use, or access such third-party websites or links. ESRPL hereby disclaims all liability or responsibility for the content hosted or made available on or products/merchandise purchased from, or information provided by you/collected from you by such third-party websites. You are advised to review the terms and conditions of such third-party websites carefully before visiting, accessing, using, or availing of the services of such third-party websites.
    </p>
    <p>Correspondence, advertisement, purchase, or promotion, including the delivery of and the payment for goods and/or services, and any other term, condition, warranty, or representation associated with such correspondence, purchase, or promotion, pertaining to such third-party website is solely between you and the applicable third party and is at your sole risk. ESRPL shall not be responsible or liable in any manner whatsoever for transactions, the information provided by / collected from you, and interaction with such third-party websites and/ or any losses sustained in that regard.</p>
    <h5 class="text-black mt-2">Intellectual Property:</h5>
    <p>All Content featured or displayed on this Website including the Team trademarks, logos, photos, pictures, audio, video, design, layout, and all other content and intellectual property rights, belongs to and is the property of ESRPL, and/or is used under valid license/authorization. Unauthorized copying, use, reproduction, distribution, modification, alteration, dissemination, reposting, hyper-linking, deep-linking, framing, mirroring, downloading, or any other use of the Content on this Website in any manner whatsoever, without the prior written authorization of ESRPL or the relevant owners, is strictly prohibited.</p>
    <h5 class="text-black mt-2">Infringement Notification:</h5>
    <p>If you believe in good faith that any Content, User Content, or material posted or otherwise made accessible on this Website, violates these Terms, is prohibited or restricted by applicable laws, rules, and regulations, violates your proprietary rights, or is abusive or threatens and harms other users of this Website, please compile the following information and email it to: contact@kochibluetigers.com ; and which email shall contain the following information:</p>
    <p>A clear identification of the allegedly prohibited/unlawful/abusive material on the Website (with specific URL reference);</p>
    <p>Your contact details: name, address, e-mail address and phone number;</p>
    <p>In case of an alleged violation of proprietary rights (including copyright, trademark or privacy rights): a statement that you believe, in good faith, that the use of the proprietary material allegedly infringed on the Website is not authorized by you or your agent or the law;</p>
    <p>A statement that you believe, in good faith, that such material is prohibited/unlawful/abusive; and</p>
    <p>A statement that the information provided in the notice is accurate, and under penalty of perjury and that the signatory is authorized to act on your behalf.</p>
    <p>The email notification provided by you under this Clause shall be executed by your electronic signature or the electronic signature of the person directly affected by the violation of these Terms by the Content or User Content.</p>
    <p>In such an event, ESRPL may contact you for any further information and reserves the right to determine, at its sole discretion, whether such Content/User Content violates these Terms or is otherwise abusive/prohibited/unlawful, and may take such action it deems appropriate. If you resort to any mala fide use of the notification process set out above, ESRPL reserves the right to restrict your access to the Website.</p>
    <h5 class="text-black mt-2">Indemnification:</h5>
    <p>You agree to defend, indemnify, and hold ESRPL and ESRPL Indemnified Parties harmless from and against any and all claims, damages, costs, and expenses, including, without limitation, attorney's fees, arising from or related to
        <ul type="i" class="list-item" style="list-style: disc">
            <li>your use of this Website,</li>
            <li>your access to, or inability to access this Website,</li>
            <li>liability arising from the illegality of or infringement by any contributions of User Content you make to the Website or from your reliance upon any information contained on this Website, or </li>
            <li>your participation in the Rewards Programme. You represent, warrant and covenant that no materials and User Content of any kind provided by you will: </li>
            <li>violate, plagiarize, or infringe upon the rights of any third party, including copyright, trademark, privacy or other personal or proprietary rights; or</li>
            <li>contain libelous or otherwise unlawful material. ESRPL reserves the right, at its own expense, to assume the exclusive defense and control of any matter subject to indemnification by you.</li>
        </ul> 
    <h5 class="text-black mt-2">Waivers:</h5>
    <p>You hereby waive any rights, whether existing or acquired in the future, that are attributable to you under any applicable law, including (without limitation) any law, regulation, or order concerned with privacy or personality rights, in relation to the matters contemplated herein, without any claim for compensation.</p>
    <h5 class="text-black mt-2">Product Information:</h5>
    <p>ESRPL cannot guarantee that the products and selections appearing on this Website will be available, either through this Website or at retail locations all the time. All product descriptions and specifications are subject to change at any time without notice. The particular technical specifications and settings of your computer/device and its display could affect the accuracy of its display of the products offered on this Website. The Content of this Website and products, selections and prices (if any) displayed on this Website do not constitute offers to sell and only constitute ESRPL's invitations to offer. As a result, ESRPL takes no responsibility for loss caused to any person based on reliance on any information on this Website and retains the right to amend or retract any Content or invitations to offer on its own terms and in its sole discretion at any time and without notice.</p>
    <h5 class="text-black mt-2">Communication:</h5>
    <p>For any questions regarding this policy, or to exercise your rights, please email us at <a class="text-black" href="mailto:contact@kochibluetigers.com">contact@kochibluetigers.com</a> </p>
    <p>If you create a User Profile and provide us with your contact information (including your e-mail address and phone number), we may contact you to provide you with information and updates, including but not limited to fixture lists and Team updates provided you have consented to receive such information. We also use such contact information to send out occasional promotional materials, including alerts on the Rewards Programme and new Services available if you have consented to receive such information subject to our Privacy Policy.</p>
    <h5 class="text-black mt-2">Assignment:</h5>
    <p>You may not assign your rights and obligations under these Terms without the prior written consent of ESRPL. ESRPL may assign its rights and obligations to a third party upon issuing written notification via an announcement on the Website.</p>
    <p>Governing law, jurisdiction, and dispute resolution:</p>
    <p>All disputes in relation to the Website and these Terms shall be governed by the laws of India, without having regard to conflict of laws, and the courts at Mumbai shall have exclusive jurisdiction to adjudicate all disputes.</p>
    <p>Notwithstanding the above, disputes and claims shall be settled by arbitration to be conducted in accordance with the Indian Arbitration and Conciliation Act, 1996, by a sole arbitrator to be appointed by ESRPL. The arbitration proceedings shall be conducted in the English language and the venue of arbitration shall be Mumbai. The arbitrator shall decide any such dispute or claim strictly in accordance with the governing law. Judgment upon any arbitral award rendered hereunder may be entered in any court having jurisdiction, or application may be made to such court for a judicial acceptance of the award and an order of enforcement, as the case may be. The costs and expenses of the arbitration, including the fees of the arbitrator shall be borne equally by each party to the dispute or claim; and each party shall pay its own fees, disbursements, and other charges of its counsel. The arbitration award shall be final, conclusive, and binding on each of the parties that were parties to the dispute</p>
    <p>Notwithstanding anything to the contrary contained anywhere in these Terms, you agree that monetary damages may not be an adequate remedy for the losses that may be sustained by ESRPL from a breach of the Terms of this Website and accordingly, ESRPL shall be entitled to seek an injunction, restraining order, right for recovery, suit for specific performance or such other equitable relief as a court of competent jurisdiction may deem necessary or appropriate to restrain you from committing any violation of these terms and conditions.</p>
    <h5 class="text-black mt-2">Non-compliance and Termination:</h5>
    <p>All disputes in relation to the Website and these Terms shall be governed by the laws of India, without having regard to conflict of laws, and the courts at Mumbai shall have exclusive jurisdiction to adjudicate all disputes. Non-compliance with any of the Terms shall result in termination of access and/or right to use the Website. ESRPL retains the right to deny access to the Website, without notice, to anyone who it believes has violated any of these Terms or does not accept these Terms.</p>
    <h5 class="text-black mt-2">Information Gathered and Tracked: </h5>
    <p>When you access this Website, your IP Address, device used to access the Website, and other demographics will be logged and recorded. If you choose to register and create a User Profile on our Website, we will collect and store such information (including personal information) as specified in Clause 3 above. All information collected from you, including information submitted for the registration of a User Profile, is subject to our Privacy Policy. We may collect further information from you if you wish to receive certain Services available on our Website, which information will be requested at the time you choose to avail of such Services. Information submitted through all feedback forms on the Website is stored in a database.</p>
</div>
    </div>
</section>